package cn.odyssey.rules;

import cn.odyssey.fact.Person
import cn.odyssey.fact.Cat

rule "demo1"
    when
        $p:Person(job=="manager" && nickNames contains "jack")
    then
        System.out.println("hello! "+$p.getName());
        if ($p.getAge() < 24) {
            System.out.println($p.getName()+"你的年龄才"+$p.getAge()+"岁啊！");
            $p.setAge($p.getAge()+10);
            update($p);
            System.out.println("但是没关系哈，10年后你就"+$p.getAge()+"岁了！");
        }
end
